export const items = [
	{ icon: "/images/Smiley.png", text: "Great Coffee" },
	{ icon: "/images/Bolt.png", text: "Fast Service" },
	{ icon: "/images/Instagram.png", text: "Cozy Space" },
	{ icon: "/images/Sweat Waterdrop.png", text: "Handcrafted Drinks" },
	{ icon: "/images/Element.png", text: "Local Roasts" },
	{ icon: "/images/Crown.png", text: "Global Flavor" },
	{ icon: "/images/Smiley Love.png", text: "Friendly Baristas" },
	{ icon: "/images/Smiley.png", text: "Great Coffee" },
	{ icon: "/images/Bolt.png", text: "Fast Service" },
	{ icon: "/images/Instagram.png", text: "Cozy Space" },
	{ icon: "/images/Sweat Waterdrop.png", text: "Handcrafted Drinks" },
	{ icon: "/images/Element.png", text: "Local Roasts" },
	{ icon: "/images/Crown.png", text: "Global Flavor" },
	{ icon: "/images/Smiley Love.png", text: "Friendly Baristas" },
]
